--QUERY 1
SELECT COUNT(SID) FROM STUDENT;
--QUERY 2
SELECT AVG(GPA) FROM STUDENT;

--QUERY 3
SELECT MIN(GPA) AS min_GPA
FROM STUDENT;
SELECT MAX(GPA) AS max_GPA
FROM STUDENT;
--QUERY 4
SELECT COUNT(SID) 
FROM STUDENT
WHERE GPA >= 3.7;

--QUERY 5
SELECT MAX(GPA),MIN(GPA),AVG(GPA),SUM(GPA)
FROM STUDENT;

--QUERY 6
SELECT COUNT(CNAME) FROM COLLEGE;

--QUERY 7
SELECT COUNT(DISTINCT(MAJOR)) AS DIFF_MAJ 
FROM APPLY;
--QUERY 8
SELECT COUNT(SID) AS APPLI 
FROM APPLY;
--QUERY 9
SELECT AVG(DISTINCT(GPA)) FROM STUDENT;

--QUERY 10
SELECT SID,CNAME,MAJOR,DECISION  FROM APPLY WHERE DECISION = 'Y';
